CREATE TABLE IF NOT EXISTS halls (
  id SERIAL PRIMARY KEY,
  row INTEGER NOT NULL,
  place INTEGER NOT NULL,
  price INTEGER NOT NULL,
  booked BOOLEAN DEFAULT FALSE
  );

CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY,
  username VARCHAR(128) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  halls_id INTEGER REFERENCES halls(id)
  );
